### ISSUE TITLE
Cannot decode character. Character maps to undefined.

### ISSUE THREAD

**Issue by blindndangerous** [YetAnotherNerd/whatlastgenre#23]
Hello,
When trying to use WLG, I get the following error.
Traceback (most recent call last):
  File "C:\Python38\Scripts\beet-script.py", line 11, in <module>
    load_entry_point('beets==1.5.0', 'console_scripts', 'beet')()
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\ui\__init__.py", line 1267, in main
    _raw_main(args)
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\ui\__init__.py", line 1254, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\ui\commands.py", line 956, in import_func
    import_files(lib, paths, query)
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\ui\commands.py", line 926, in import_files
    session.run()
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\util\pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "C:\Python38\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\util\pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\util\pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\importer.py", line 1513, in plugin_stage
    func(session, task)
  File "C:\Python38\lib\site-packages\beets-1.5.0-py3.8.egg\beets\plugins.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\blindndangerous\AppData\Roaming\wlgsource\plugin\beets\beetsplug\wlg.py", line 118, in imported
    self.setup()
  File "C:\Users\blindndangerous\AppData\Roaming\wlgsource\plugin\beets\beetsplug\wlg.py", line 65, in setup
    self.wlg = whatlastgenre.WhatLastGenre(conf)
  File "C:\Python38\lib\site-packages\whatlastgenre-0.2.1-py3.8.egg\wlg\whatlastgenre.py", line 63, in __init__
  File "C:\Python38\lib\site-packages\whatlastgenre-0.2.1-py3.8.egg\wlg\whatlastgenre.py", line 79, in read_whitelist
  File "C:\Python38\lib\site-packages\whatlastgenre-0.2.1-py3.8.egg\wlg\whatlastgenre.py", line 829, in read_datafile
  File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 9440: character maps to <undefined>
This seems to have something to do with the character map, but I can't figure out what, or how to fix it.

**Comment by blindndangerous** [comment]
Looking at the forks of this, I think @slogsdon7 fixed my error.  At least after using their's, I'm not getting the error anymore. https://github.com/slogsdon7/whatlastgenre
